// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NDISS.NotificationService.API.Data;

#nullable disable

namespace NDISS.NotificationService.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NDISS.NotificationService.API.Domain.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRepeat")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RepeatPeriod")
                        .HasColumnType("datetime2");

                    b.HasKey("NotificationId");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NDISS.NotificationService.API.Domain.NotificationEvent", b =>
                {
                    b.Property<string>("NotificationEventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ErrorReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventStatus")
                        .HasColumnType("int");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NotificationMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("NotificationEventId");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationEvents");
                });

            modelBuilder.Entity("NDISS.NotificationService.API.Domain.NotificationType", b =>
                {
                    b.Property<string>("NotificationTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NotificationTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            NotificationTypeId = "1",
                            NotificationTypeName = "SMS"
                        },
                        new
                        {
                            NotificationTypeId = "2",
                            NotificationTypeName = "Email"
                        });
                });

            modelBuilder.Entity("NDISS.NotificationService.API.Domain.Notification", b =>
                {
                    b.HasOne("NDISS.NotificationService.API.Domain.NotificationType", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("NDISS.NotificationService.API.Domain.NotificationEvent", b =>
                {
                    b.HasOne("NDISS.NotificationService.API.Domain.Notification", "Notification")
                        .WithMany("NotificationEvents")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("NDISS.NotificationService.API.Domain.Notification", b =>
                {
                    b.Navigation("NotificationEvents");
                });

            modelBuilder.Entity("NDISS.NotificationService.API.Domain.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
