// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NDISS.Service.API.Data;

#nullable disable

namespace NDISS.Service.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NDISS.Service.API.Domain.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderServiceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryId");

                    b.HasIndex("ProviderServiceId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.Item", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderServiceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ItemId");

                    b.HasIndex("ProviderServiceId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.Menu", b =>
                {
                    b.Property<string>("MenuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PeriodId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MenuId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PeriodId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.MenuItem", b =>
                {
                    b.Property<string>("MenuItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MenuId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MenuItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.Period", b =>
                {
                    b.Property<string>("PeriodId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PeriodId");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.ProviderService", b =>
                {
                    b.Property<string>("ProviderServiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProviderServiceId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("ProviderServices");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.ProviderServiceLocation", b =>
                {
                    b.Property<string>("ProviderServiceLocationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderServiceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderServiceLocationAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderServiceLocationCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProviderServiceLocationLat")
                        .HasColumnType("real");

                    b.Property<float>("ProviderServiceLocationLong")
                        .HasColumnType("real");

                    b.Property<int>("ProviderServiceLocationPostcode")
                        .HasColumnType("int");

                    b.Property<string>("ProviderServiceLocationState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProviderServiceLocationId");

                    b.HasIndex("ProviderServiceId");

                    b.ToTable("ProviderServiceLocations");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.ServiceType", b =>
                {
                    b.Property<string>("ServiceTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceTypeId");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.SinglePlan", b =>
                {
                    b.Property<string>("SinglePlanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MenuId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WeekDayId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WeeklyPlanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SinglePlanId");

                    b.HasIndex("MenuId");

                    b.HasIndex("WeekDayId");

                    b.HasIndex("WeeklyPlanId");

                    b.ToTable("SinglePlans");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.WeekDay", b =>
                {
                    b.Property<string>("WeekDayId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WeekDayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeekDayId");

                    b.ToTable("WeekDays");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.WeeklyPlan", b =>
                {
                    b.Property<string>("WeeklyPlanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PlanPrice")
                        .HasColumnType("real");

                    b.HasKey("WeeklyPlanId");

                    b.HasIndex("CategoryId");

                    b.ToTable("WeeklyPlans");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.Category", b =>
                {
                    b.HasOne("NDISS.Service.API.Domain.ProviderService", "ProviderService")
                        .WithMany("Categories")
                        .HasForeignKey("ProviderServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderService");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.Item", b =>
                {
                    b.HasOne("NDISS.Service.API.Domain.ProviderService", "ProviderService")
                        .WithMany("Items")
                        .HasForeignKey("ProviderServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderService");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.Menu", b =>
                {
                    b.HasOne("NDISS.Service.API.Domain.Category", "Category")
                        .WithMany("Menus")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NDISS.Service.API.Domain.Period", "Period")
                        .WithMany("Menus")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.MenuItem", b =>
                {
                    b.HasOne("NDISS.Service.API.Domain.Item", "Item")
                        .WithMany("MenuItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NDISS.Service.API.Domain.Menu", "Menu")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.ProviderService", b =>
                {
                    b.HasOne("NDISS.Service.API.Domain.ServiceType", "ServiceType")
                        .WithMany("ProviderServices")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.ProviderServiceLocation", b =>
                {
                    b.HasOne("NDISS.Service.API.Domain.ProviderService", "ProviderService")
                        .WithMany("ProviderServiceLocations")
                        .HasForeignKey("ProviderServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderService");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.SinglePlan", b =>
                {
                    b.HasOne("NDISS.Service.API.Domain.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NDISS.Service.API.Domain.WeekDay", "WeekDay")
                        .WithMany("SinglePlans")
                        .HasForeignKey("WeekDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NDISS.Service.API.Domain.WeeklyPlan", "WeeklyPlan")
                        .WithMany("SinglePlans")
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("WeekDay");

                    b.Navigation("WeeklyPlan");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.WeeklyPlan", b =>
                {
                    b.HasOne("NDISS.Service.API.Domain.Category", "Category")
                        .WithMany("WeeklyPlans")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.Category", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("WeeklyPlans");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.Item", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.Menu", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.Period", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.ProviderService", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Items");

                    b.Navigation("ProviderServiceLocations");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.ServiceType", b =>
                {
                    b.Navigation("ProviderServices");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.WeekDay", b =>
                {
                    b.Navigation("SinglePlans");
                });

            modelBuilder.Entity("NDISS.Service.API.Domain.WeeklyPlan", b =>
                {
                    b.Navigation("SinglePlans");
                });
#pragma warning restore 612, 618
        }
    }
}
