// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NDISS.UserRebate.API.Data;

#nullable disable

namespace NDISS.UserRebate.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250612131258_Enums")]
    partial class Enums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NDISS.UserRebate.API.Domain.RebateEvent", b =>
                {
                    b.Property<string>("RebateEventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("RebateEventTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRebateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RebateEventId");

                    b.HasIndex("RebateEventTypeId");

                    b.HasIndex("UserRebateId");

                    b.ToTable("RebateEvents");
                });

            modelBuilder.Entity("NDISS.UserRebate.API.Domain.RebateEventType", b =>
                {
                    b.Property<string>("RebateEventTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RebateEventTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RebateEventTypeId");

                    b.ToTable("RebateEventTypes");
                });

            modelBuilder.Entity("NDISS.UserRebate.API.Domain.RebateRetrySchedule", b =>
                {
                    b.Property<string>("ScheduleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RebateEventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("RetryReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleId");

                    b.HasIndex("RebateEventId");

                    b.ToTable("RebateRetrySchedules");
                });

            modelBuilder.Entity("NDISS.UserRebate.API.Domain.UserRebate", b =>
                {
                    b.Property<string>("UserRebateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("RebateRate")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserRebateId");

                    b.ToTable("UserRebates");
                });

            modelBuilder.Entity("NDISS.UserRebate.API.Domain.RebateEvent", b =>
                {
                    b.HasOne("NDISS.UserRebate.API.Domain.RebateEventType", "RebateEventType")
                        .WithMany("RebateEvents")
                        .HasForeignKey("RebateEventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NDISS.UserRebate.API.Domain.UserRebate", "UserRebate")
                        .WithMany("RebateEvents")
                        .HasForeignKey("UserRebateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RebateEventType");

                    b.Navigation("UserRebate");
                });

            modelBuilder.Entity("NDISS.UserRebate.API.Domain.RebateRetrySchedule", b =>
                {
                    b.HasOne("NDISS.UserRebate.API.Domain.RebateEvent", "RebateEvent")
                        .WithMany("RebateRetrySchedules")
                        .HasForeignKey("RebateEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RebateEvent");
                });

            modelBuilder.Entity("NDISS.UserRebate.API.Domain.RebateEvent", b =>
                {
                    b.Navigation("RebateRetrySchedules");
                });

            modelBuilder.Entity("NDISS.UserRebate.API.Domain.RebateEventType", b =>
                {
                    b.Navigation("RebateEvents");
                });

            modelBuilder.Entity("NDISS.UserRebate.API.Domain.UserRebate", b =>
                {
                    b.Navigation("RebateEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
